SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE announcements;
TRUNCATE blotter;
TRUNCATE complainant;
TRUNCATE complaint_type;
TRUNCATE editprofile;
TRUNCATE employee;
TRUNCATE employee_program_assignment;
TRUNCATE hearing_schedule;
TRUNCATE household;
TRUNCATE participants;
TRUNCATE program;
TRUNCATE program_expense;
TRUNCATE requests;
TRUNCATE request_type;
TRUNCATE resident;
TRUNCATE transactions;
TRUNCATE respondents;
SET FOREIGN_KEY_CHECKS = 1;